Update sbc-common-component version number
bcgov/business-filings-ui pull request #220
Opened 2021-06-02 21:35 UTC by eve-git

Update sbc-common-component version number

*Issue #:* /bcgov/entity#6682

*Description of changes:*
Update sbc-common-component version number

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

2021-06-02 22:49 UTC, eve-git commented
Unit test is passed. Ready to merge.

2021-06-03 17:01 UTC, severinbeauvais commented
^^ I'm not worrying about the code coverage check.

2021-06-03 21:10 UTC, severinbeauvais approved these changes
LGTM!

No issues with testing? Do you want other reviewers, or can I merge this?

2021-06-03 21:10 UTC, severinbeauvais commented
^^ I don't have a problem with the code coverage check.

2021-06-03 21:12 UTC, severinbeauvais requested changes
See my new comment.

2021-06-03 21:12 UTC, severinbeauvais commented on package.json
> +    "sbc-common-components": "^2.4.18",
Remove ^.

2021-06-03 22:26 UTC, eve-git commented on package.json
> +    "sbc-common-components": "^2.4.18",
done

2021-06-03 22:28 UTC, severinbeauvais approved these changes
LGTM.

@andrepestana-aot If you approve, please merge.

2021-06-03 23:14 UTC, andrepestana-aot approved these changes
👍

2021-06-03 23:14 UTC, merged